build:
	pandoc -t html5 brie.md -H nav.html -c style.css -s -o brie.html
	pandoc -t html5 syntax.md -H nav.html -c style.css -s -o syntax.html
	pandoc -t html5 types.md -H nav.html -c style.css -s -o types.html
	cp brie.html index.html

